### ISSUE TITLE
Executable / app names

### ISSUE THREAD

**Issue by basxto** [Dariasteam/Cows-Revenge#10]
I would recommend just using:
* CowsRevenge.apk (Android)
* CowsRevenge.exe (Windows)
* CowsRevenge.x86_64 (Linux)
* CowsRevenge.app.zip (Mac, folder inside should then be CowsRevenge.app)

On Linux extensions don’t matter, but this and `.bin.x86_64` is what [I’ve seen most](https://mikemaximus.github.io/gbm-web/GBM_Official_Linux.xml).
For Linux packages `cowsrevenge` remains best, since it’s installed globally and should be memorable.
Right now detection regex for itch.io,  github realease and flatpak would be `(C|c)ow.?s.?(R|r)evenge.*(-.GNU.Linux.X11)?`, other would just be `(C|c)ows(R|r)evenge(\.x68(_64)?)?`.
Godot officially support to also build a 32-bit version for x86.
Unlike Windows and Mac, Linux supports a great amount of different hardware platforms.
It looks like godot [could](https://www.reddit.com/r/godot/comments/6dvegl/godot_on_the_raspberry_pi/) work on Raspberry Pi (ARM).
If started from terminal, the itch.io release looks like this: ` ./Cow\'s\ Revenge\ \ -\ GNU⁄Linux\ X11` (The slash in GNU/Linux isn’t even a regular slash)

**Comment by Dariasteam** [comment]
Fun fact: I just been the entire day trying to build the game in a raspberry but archived nothing. Tomorrow will think more about the names thing.

**Comment by basxto** [comment]
This https://github.com/crabcrabcam/godot/releases/tag/2.1.4-stable-export?

**Comment by Dariasteam** [comment]
Names changed

**Comment by basxto** [comment]
Thanks.
And there is the x in [x86](https://en.wikipedia.org/wiki/X86) missing

**Comment by Dariasteam** [comment]
Oops, you are right. Fixed now.

**Comment by Dariasteam** [comment]
Also I don't know why but the mac version always upload with a different name. "cows-revenge-mac.zip" despite being the one you said when exported from godot.
