### ISSUE TITLE
Addition to F-Droid listing

### ISSUE THREAD

**Issue by HenriDellal** [Dariasteam/Cows-Revenge#2]
Hello.
Thank you for this game, I enjoy it a lot. It would be cool to see this game on F-Droid. [F-Droid](https://www.f-droid.org/) is an app store for Android that distributes FOSS software. If you agree to have the game added in F-Droid, please give an agreement.
Thanks.

**Comment by Dariasteam** [comment]
Hey! I'm glad you like it. About F-Droid, I'ts a bit embarrasing, I've tried to submit twice but there was always an error here and there and I never managed to fix it. [Here is my merge request](https://gitlab.com/fdroid/fdroiddata/merge_requests/3069) If you have any suggestion or know how to fix it, please tell me, I really want this game to be there!

**Comment by HenriDellal** [comment]
I suppose that @w84death and @HassanHeydariNasab know it as they have Godot games on F-Droid. I mention them so they can see the post.

**Comment by Dariasteam** [comment]
Hey, I forgot to answer here. Hassan helped me and now I'm waiting for fdroid reviewers. Thanks for mentioning it!

**Comment by Dariasteam** [comment]
The game is published im fdroid.
