### ISSUE TITLE
Exit button in main menu

### ISSUE THREAD

**Issue by basxto** [Dariasteam/Cows-Revenge#6]
On android and also with gamepad it would be helpful to have a exit button for closing the game
Right now one has to kill the app on android

**Comment by Dariasteam** [comment]
You mean not hepfull in android when you are not using gamepad right? I can allow using the native android back button in that screen to close it.

**Comment by basxto** [comment]
The native back button already works, but you have to swipe in the controls first.

**Comment by Dariasteam** [comment]
I would swear I had disabled it to avoid exiting in the middle of a level. Need to fix that. About the corner button, something like this? 
![imagen](https://user-images.githubusercontent.com/9285997/45599234-c6442380-b9df-11e8-9618-9833c9c8079f.png)

**Comment by basxto** [comment]
yes, something like that

**Comment by Dariasteam** [comment]
Pushed, both cancel button and on screen button methods https://github.com/Dariasteam/Cows-Revenge/commit/192150594e3e95fb29faf285c83460f16b2ffa45
